mitex-rs/mitex

crates/mitex/src/lib.rs
When it meets an unknown command, typst will report:
```
error: plugin errored with: error: unknown command: \abc
```
instead of:
```
error: plugin panicked: wasm `unreachable` instruction executed
```
=> dev(converter): raise error to typst instead of panic

crates/mitex-parser/benches/simple.rs
- Add [allocation profiling](https://nikolaivazquez.com/blog/divan/#measure-allocations). I have [carefully optimized it](https://github.com/nvzqz/divan/blob/main/CHANGELOG.md#018---2023-12-19) so it should not have a noticeable footprint.
- Remove setup cost from benchmarks. Previously benchmarks would include the cost of initializing a `once_cell::sync::Lazy` instance. This reduces benchmarked times by 100-400µs.
Example output:
```
simple                  fastest       │ slowest       │ median        │ mean          │ samples │ iters
├─ alpha_x_20000        1.975 ms      │ 2.168 ms      │ 1.99 ms       │ 1.995 ms      │ 100     │ 100
│                       alloc:        │               │               │               │         │
│                         12          │ 12            │ …
```
=> Improve benchmarks

build.sh, scripts/build.sh
+ Only build `mitex-typst` for wasm.
+ remove `typst-package/mitex.wasm` forcely.
+ move build.sh
=> dev: improve build script

Cargo.lock, crates/mitex-parser/src/lib.rs, crates/mitex-spec/Cargo.toml, crates/mitex-spec/benches/constructions.rs, crates/mitex-spec/src/lib.rs, crates/mitex-spec/src/preludes.rs, crates/mitex-spec/src/query.rs, crates/mitex-spec/src/stream.rs, crates/mitex-typst/Cargo.toml, crates/mitex-typst/src/lib.rs, crates/mitex/src/lib.rs, typst-package/mitex.typ
+ move command preludes to `mitex_spec` for benchmark.
+ add JSON and rkyv serialization to `mitex_spec::CommandSpec`, see crates/mitex-spec/benches/constructions.rs for performance comparison.
+ add compile_spec api to WASM library
+ but we don't provide it by package, since it is not mature enough.
+ add `spec` optional argument to `mitex-convert` API. I have benchmarked it by `typst-package/examples/bench.typ`, so far so good.
=> feat: add compile_spec api to WASM library

crates/mitex-typst/src/lib.rs
We currently don't need to have it. By removing it, the size of wasm binary comes to 185KB
=> dev: disable compile_spec api

crates/mitex-lexer/src/lib.rs, crates/mitex-lexer/src/macro_engine.rs, crates/mitex-lexer/tests/expand_macro.rs, crates/mitex-parser/benches/simple.rs, crates/mitex-parser/src/lib.rs, crates/mitex-parser/src/parser.rs, crates/mitex-parser/src/syntax.rs, crates/mitex/benches/convert_large_projects.rs, crates/mitex/src/lib.rs
MiTeX starts to support macro evaluation. Currently it simply removes all macro definitions, which is still an improvement. For example,
```
\newcommand{\x}{y}
f(x)
```
Before, it is converted into
```
{\x}{y}
f(x)
```
After, it is converted into:
```
f(x)
```
Nevertheless, if users doesn't use macros at all, the performance keeps same:
```
baseline (mitex v0.1.0, typst v0.10.0)
Benchmark 1: typst compile --root . crates\mitex\benches\empty.typ
Time (mean ± σ):     379.0 ms ±   8.8 ms    [User: 101.2 ms, System: 32.8 ms]
Range (min … max):   369.9 ms … 396.6 ms    10 runs
Benchmark 1: typst compile --root . crates\mitex\benches\oiwiki.typ
Time (mean ± σ):      2.214 s ±  0.073 s    [User: 0.469 s, System: 0.031 s]
Range (min … max):    2.096 s …  2.316 s    10 runs
Benchmark 1: typst …
```
=> dev(m_engine): switch to lexer with macro engine

crates/mitex-lexer/src/lib.rs, crates/mitex-lexer/src/macro_engine.rs, crates/mitex-lexer/tests/expand_macro.rs, crates/mitex-parser/src/parser.rs, crates/mitex-parser/src/syntax.rs, crates/mitex-parser/tests/common/mod.rs, crates/mitex/src/lib.rs, packages/mitex/examples/example.typ
These commands are supported
- \newcommand
- \newcommand*
- \renewcommand
- \renewcommand*
- \DeclareRobustCommand
- \DeclareRobustCommand*
- \providecommand
- \providecommand*
Also MiTeX provides an extra `\mitexrecurse` for defining commands recursively. For example:
```tex
\newcommand{\DeclarePairedDelimiter}[2]{
\newcommand{#1}[1]{\left#2\mitexrecurse{#1}\right#2}
}
\DeclarePairedDelimiter{\abs}{\vert}
\abs{abc}
```
Which is equivalent to `|abc|`
`\mitexrecurse` is not for users, but useful when we define commands in spec.typ files.
=> feat(m_engine): fully support to recursive macro command expansion

crates/mitex-spec/src/lib.rs, crates/mitex-spec/src/query.rs, docs/spec.typ
I edited the comment text in spec.typ for clarity.
=> docs: edit spec document and comments for clarity

crates/mitex-lexer/src/lib.rs, crates/mitex-lexer/src/macro_engine.rs, crates/mitex-lexer/tests/expand_macro.rs
These commands are supported
- \newenvironment
- \newenvironment*
- \renewenvironment
- \renewenvironment*
=> feat(m_engine): support {{,re}new} environment

.github/workflow/lint_pr_title.yml
PR with invalid title will fail on this action.
types available here: https://github.com/commitizen/conventional-commit-types
an extra type is introduced `dev` which marks internal development.
=> feat(ci): add linting action for PR title

crates/mitex-lexer/src/lib.rs, crates/mitex-lexer/src/macro_engine.rs, crates/mitex-lexer/tests/expand_macro.rs, crates/mitex-parser/src/parser.rs, crates/mitex-parser/src/syntax.rs, crates/mitex-parser/tests/ast.rs, crates/mitex-parser/tests/ast/block_comment.rs, crates/mitex-parser/tests/common/mod.rs, crates/mitex/src/lib.rs
These commands are supported
+ \iffalse
+ \iftrue
+ \iftypst
Also supports `\iftypst`, see: 
```rs
#[test]
fn test_convert_typst_code() {
assert_snapshot!(convert_math(r#"\iftypst#show: template\fi"#).unwrap(), @"#show: template");
assert_snapshot!(convert_math(r#"\iftypst#import "template.typ": project
#show: project\fi"#).unwrap(), @r###"
#import "template.typ": project
#show: project
"###);
}
```
=> feat(m_engine): support if{false,true,typst} conditional macros

crates/mitex-lexer/src/macro_engine.rs, crates/mitex-lexer/tests/expand_macro.rs
If not, arithmetic overflow happens if `num_args` equals to `0`.
=> fix(lexer): test number of macro arguments before reading them

.github/workflows/ci.yml, .gitmodules, Cargo.lock, Cargo.toml, crates/mitex-lexer/Cargo.toml, crates/mitex-parser/Cargo.toml, crates/mitex-spec-gen/Cargo.toml, crates/mitex-spec-gen/build.rs, crates/mitex-spec-gen/src/lib.rs, crates/mitex/Cargo.toml, scripts/build.ps1, scripts/build.sh
The key code is here
https://github.com/mitex-rs/mitex/blob/ed4a57cbe7ac9a7668ff4fc019a120633c63d76f/crates/mitex-spec-gen/build.rs#L10-L17
Three mode.
+ if specified feature `prebuilt`, get spec by running `copy_prebuilt`.
+ otherwise, if specified feature `generate`, get spec by running `generate`.
+ otherwise, in default, if users have typst-cli installed, run `generate`, otherwise run `copy_prebuilt`.
```rs
if which::which("typst").is_ok() { 
generate 
} else { 
// fallback to prebuilt spec 
copy_prebuilt 
}
```
=> feat: generate cmd spec or use prebuilt cmd spec in build.rs

README.md, crates/mitex-cli/src/main.rs, crates/mitex-spec-gen/build.rs, crates/mitex-spec/src/lib.rs
+ Add cli usage to readme.
+ Use new text mode in compile command
+ Restrict build constraints for mitex-cli, so that it doesn't always compile by `cargo run --bin mitex`.
+ insert handler definitions in `mitex-scope` before the transpiled document. They look like:
```typ
#import "@preview/mitex:0.1.0": *
#let mitexarray = mitex-scope.at("mitexarray", default: none);
#let mitexbold = mitex-scope.at("mitexbold", default: none);
#let mitexcal = mitex-scope.at("mitexcal", default: none);
...
```
=> dev(cli): fix readme, command, build script, and compile result

.github/workflows/github_pages.yml
https://vitejs.dev/guide/build#public-base-path
=> fix: set base in gh pages workflow

Cargo.lock, Cargo.toml, fuzz/mitex/Cargo.toml, fuzz/mitex/src/main.rs
First prepare a bunch of tex input, I suggest the top 50 of oiwiki:
```js
const test = require('./oiwiki-231222.json')
const fs = require('fs');
// write each test case to a file in a subdirectory
for (const [i, t] of test.entries()) {
fs.writeFileSync(`./seed/${i}.txt`, t.text);
if (i > 50) {
break;
}
}
```
Then build and fuzz
```
cargo afl build --bin fuzz-target-mitex
cargo afl fuzz -i local/seed -o local/fuzz-res ./target/debug/fuzz-target-mitex
```
To minimize test case, using afl-tmin
```
cargo afl tmin -i crash.tex -o minimized.tex ./target/debug/fuzz-target-mitex
```
=> test: add afl fuzzer

packages/mitex/specs/latex/standard.typ
Should resolve #121. 
If there are additional changes that need to happen, please let me know and I'll make them. Also feel free to just edit the PR.
=> fix: remove extra spacing for ceiling symbols

crates/mitex-lexer/src/token.rs, crates/mitex-parser/src/parser.rs, crates/mitex-parser/src/syntax.rs, crates/mitex-parser/tests/common/mod.rs, crates/mitex/src/lib.rs
Not too sure on some of the organization, particularly treating `\(` and `\[` as dollars syntactically. 
```typst
#import "packages/mitex/mitex.typ": *
= Converted
#let test_text = "
\\(1 + 2\\)
\\[1 + 2\\]
"
#raw(mitex-convert(mode: "text", test_text))
= Rendered
#eval(
mitex-convert(mode: "text", test_text), mode: "markup", scope: mitex-scope,
)
```
gives 
Closes #124
=> feat: add support for `\(\)` and `\[\]` instead of `$`'s

crates/mitex-lexer/src/token.rs, crates/mitex-parser/src/parser.rs, crates/mitex-parser/src/syntax.rs, crates/mitex-parser/tests/ast.rs, crates/mitex-parser/tests/ast/formula.rs, crates/mitex-parser/tests/common/mod.rs, crates/mitex/src/lib.rs
I have refactored the parser and added some tests for formulas.
During testing, I find a bug:
https://github.com/mitex-rs/mitex/blob/b85675ab1eba8774894948091432765fb433f1cc/crates/mitex/src/lib.rs#L1151-L1156
And two optional semantic errors to handle: 
https://github.com/mitex-rs/mitex/blob/b85675ab1eba8774894948091432765fb433f1cc/crates/mitex/src/lib.rs#L1157-L1168
=> refactor: improve formula parser

crates/mitex-parser/src/parser.rs, crates/mitex-parser/tests/ast.rs, crates/mitex-parser/tests/ast/arg_parse.rs, crates/mitex-parser/tests/ast/formula.rs
Fix #130. #130 should be closed since this PR fix the first point of #130 and the second point of #130 is duplicated. 
This is the case to fix:
https://github.com/mitex-rs/mitex/blob/d75f54bf4c265d369d5c445edfb5e99bab94b3fc/crates/mitex-parser/tests/ast/formula.rs#L34-L42
All bracket/paren are viewed as normal text if they are not matched as an argument of some command.
=> fix: parse bracket/paren group only if as argument

README.md, crates/mitex-cli/src/main.rs, fixtures/underleaf/ieee/main.typ, packages/mitex-web/src/main.ts, packages/mitex/README.md, packages/mitex/examples/example.typ, packages/mitex/typst.toml
bump version to 0.2.2
1. **Urgent fix:** remove duplicate keys for error when a dict has duplicate keys in 0.11
2. fix: parse bracket/paren group
3. fix: remove extra spacing for ceiling symbols
4. feat: add support for `\(\)` and `\[\]`
5. feat: support footnote and cite
=> chore: bump version to 0.2.2

crates/mitex-lexer/src/token.rs, crates/mitex-parser/src/parser.rs, crates/mitex-parser/src/syntax.rs, crates/mitex-parser/tests/ast/command.rs, crates/mitex-parser/tests/common/mod.rs, crates/mitex/src/lib.rs, packages/mitex/examples/example.typ, packages/mitex/specs/latex/standard.typ
=> refactor: convert \text{} to \textmath[]

crates/mitex-parser/src/arg_match.rs, crates/mitex-parser/src/parser.rs, crates/mitex-spec/Cargo.toml, crates/mitex-spec/benches/spec_constructions.rs, crates/mitex-spec/src/lib.rs, crates/mitex-spec/src/preludes.rs, crates/mitex-spec/src/query.rs, crates/mitex/src/converter.rs
To document all structs, I merged the undocumented command spec structs for json format into the that for rkyv format.
=> dev: merge command spec structs for json and rkyv

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, crates/mitex-cli/src/main.rs, fixtures/underleaf/ieee/main.typ, packages/mitex-web/src/main.ts, packages/mitex/CHANGELOG.md, packages/mitex/README.md, packages/mitex/typst.toml
- Fix `\boxed` command.
- Support basic figure and tabular environments.
- Add escape symbols for plus, minus and percent.
- Fix `\left` and `\right`: size of lr use em.
=> chore: bump version to 0.2.4

.gitmodules, Cargo.lock, Cargo.toml, crates/mitex-cli/Cargo.toml, crates/mitex-lexer/Cargo.toml, crates/mitex-parser/Cargo.toml, crates/mitex-spec-gen/Cargo.toml, crates/mitex-spec-gen/build.rs, crates/mitex-spec-gen/src/lib.rs, crates/mitex-spec/Cargo.toml, crates/mitex-wasm/Cargo.toml, crates/mitex/Cargo.toml, scripts/publish.ps1
- Preview documents on docs.rs: https://docs.rs/releases/search?query=mitex
- now we can get `mitex` with `cargo`:
```bash
cargo install mitex-cli --version 0.2.2-rc2
```
=> build: improve crates metadata for publish

crates/mitex-lexer/src/macro_engine.rs
Some tokens may not get macro expanded and directly pushed to parsers (outer stream), which will cause failures of conversion.
=> fix: fetch a token only if there is no token is peeking
